version: '3.8'

services:
  backend:
    build: ./backend
    deploy:
      resources:
        limits:
          cpus: "0.5"    # Use only half of a CPU core
          memory: 512M   # Use a maximum of 512 MB RAM
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
